package com.gw.dm;

import java.util.Arrays;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

import com.gw.dm.entity.EntityLizalfos;
import com.gw.dm.proxy.CommonProxy;
import com.gw.dm.util.AudioHandler;
import com.gw.dm.util.ConfigHandler;
import com.gw.dm.util.DMGenerationHandler;
import com.gw.dm.util.MiscRegistrar;
import com.gw.dm.util.MobRegistrar;

@Mod(modid = DungeonMobs.MODID, name = "Dungeon Mobs", version = DungeonMobs.VERSION, 
	 dependencies = "after:dldungeonsjbg")
public class DungeonMobs {
	public static final String MODID = "dungeonmobs";
	public static final String VERSION = "5.4.1";

	@Instance(MODID)
	public static DungeonMobs instance;
	DMGenerationHandler worldGen;
	
	private static boolean gotDLD;

	@SidedProxy(clientSide = "com.gw.dm.proxy.ClientProxy",
			serverSide = "com.gw.dm.proxy.CommonProxy")
	public static CommonProxy proxy;


	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modmeta = event.getModMetadata();
		modmeta.authorList = Arrays.asList(new String[]{"GnomeWorks", "JaredBGreat", "Sunconure"});
		modmeta.autogenerated = false;
		modmeta.credits = "_303, ZeuX, r4wk, Zorn_Taov, Wreckage, Crudedragos, DraxisWuf, MohawkyMagoo";
		modmeta.description =
				"Adds a variety of new hostile mobs, all of which hate you.\n" +
						"Inspiration includes: Dungeons & Dragons, Legend of Zelda\n" +
						"\n" +
						"Rust Monster - Ghoul - Shrieker - Umber Hulk - Hook Horror "
						+ "- Beholder - Troll - Cave Fisher - Destrachan - Illithid "
						+ "- Hell Hound - Rakshasa - Lizalfos - Cockatrice - Manticore "
						+ "- Thoqqua - Vescavor - Revenant - Vampire - Fallen Angel - Outer Thing\n";
		modmeta.url = "http://www.minecraftforum.net/topic/231082-"; // FIXME: New page


		ConfigHandler.configDir = ConfigHandler.findConfigDir(event.getModConfigurationDirectory());
		ConfigHandler.init();

		MiscRegistrar.initBlocks();
		
		
		MobRegistrar.registerMobs();
		if (ConfigHandler.spawnNaturally) {
			MobRegistrar.registerSpawns();
		}
		if (ConfigHandler.addToVanillaDungeons) {
			MobRegistrar.addToVanillaDungeons();
		}
		proxy.registerRenders();		
	}


	@EventHandler
	public void init(FMLInitializationEvent event) {
		AudioHandler.registerSounds();
		if(ConfigHandler.spawnBladeTrap) {
			worldGen = new DMGenerationHandler();
		}
		if (gotDLD && ConfigHandler.addToDoomlikeDungeons) {
			MobRegistrar.addToDLD();
		}
	}


	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		initMonsterSpecialData();
	}
	
	
	private static void initMonsterSpecialData() {
		EntityLizalfos.initLocations();
		DMGenerationHandler.initTargetBlocks();
		ConfigHandler.mobSpecialSetup();
	}
	
	
	private static void testDLD() {
		gotDLD = net.minecraftforge.fml.common.Loader.isModLoaded("DLDungeonsJBG") 
						 || net.minecraftforge.fml.common.Loader.isModLoaded("dldungeonsjbg");	
	}

}
